---
- name: AZURE CREATE W2012 R2 SERVER
  hosts: localhost
  vars:
    my_resource_group: MyResourceGroup
    my_vm_name: anspocw2012
    my_vn_name: poc-vn
    my_sn_name: poc-sn
    winrm_enable_script: SQBuAHYAbwBrAGUALQBFAHgAcAByAGUAcwBzAGkAbwBuACAALQBDAG8AbQBtAGEAbgBkACAAKAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQAKQAuAEQAbwB3AG4AbABvAGEAZABTAHQAcgBpAG4AZwAoACcAaAB0AHQAcABzADoALwAvAHIAYQB3AC4AZwBpAHQAaAB1AGIAdQBzAGUAcgBjAG8AbgB0AGUAbgB0AC4AYwBvAG0ALwBhAG4AcwBpAGIAbABlAC8AYQBuAHMAaQBiAGwAZQAvAGQAZQB2AGUAbAAvAGUAeABhAG0AcABsAGUAcwAvAHMAYwByAGkAcAB0AHMALwBDAG8AbgBmAGkAZwB1AHIAZQBSAGUAbQBvAHQAaQBuAGcARgBvAHIAQQBuAHMAaQBiAGwAZQAuAHAAcwAxACcAKQApADsAIABFAG4AYQBiAGwAZQAtAFcAUwBNAGEAbgBDAHIAZQBkAFMAUwBQACAALQBSAG8AbABlACAAUwBlAHIAdgBlAHIAIAAtAEYAbwByAGMAZQA=

  tasks:
  - name: CREATE AZURE STORAGE ACCOUNT
    azure_rm_storageaccount:
      subscription_id: "{{ my_subscription_id }}"
      client_id: "{{ my_client_id }}"
      secret: "{{ my_secret }}"
      tenant: "{{ my_tenant }}"
      name: '{{ my_vm_name }}'
      resource_group: "{{ my_resource_group }}"
      account_type: Standard_LRS

  - name: PROVSION VIRTUAL HOST
    azure_rm_virtualmachine:
      subscription_id: "{{ my_subscription_id }}"
      client_id: "{{ my_client_id }}"
      secret: "{{ my_secret }}"
      tenant: "{{ my_tenant }}"
      admin_username: richard
      admin_password: "{{ my_admin_password }}"
      os_type: Windows
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2012-R2-Datacenter
        version: latest
      name: "{{ my_vm_name }}"
      resource_group: "{{ my_resource_group }}"
      state: present
      vm_size: Standard_D1
      storage_account_name: "{{ my_vm_name }}"
      virtual_network_name: "{{ my_vn_name }}"
      subnet_name: "{{ my_sn_name }}"

  - name: CREATE AZURE VM EXTENSION TO ENABLE HTTPS WINRM LISTENER
    azure_rm_virtualmachine_extension:
      subscription_id: "{{ my_subscription_id }}"
      client_id: "{{ my_client_id }}"
      secret: "{{ my_secret }}"
      tenant: "{{ my_tenant }}"
      name: winrm-extension
      resource_group: "{{ my_resource_group }}"
      virtual_machine_name: "{{ my_vm_name }}"
      publisher: Microsoft.Compute
      virtual_machine_extension_type: CustomScriptExtension
      type_handler_version: 1.9
      settings: '{"commandToExecute": "powershell.exe -ExecutionPolicy ByPass -EncodedCommand {{winrm_enable_script}}"}'
      auto_upgrade_minor_version: true

  - name: WAIT FOR WINRM TO GO ONLINE
    wait_for:
      port: 5986
      host: '{{azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress}}'
      timeout: 600

  - name: GENERATE SECURITY UPDATE REPORT
    win_updates:
      category_names: SecurityUpdates
      state: searched
      log_path: /var/log/winsecurity/ansible_wu.txt
    tags: gsur

  - name: INSTALL SECURITY UPDATES
    win_updates:
      category_names: SecurityUpdates
      state: installed
    tags: gsur
