---
- name: PATCH AZURE VM
  hosts: all

  tasks:
  - name: Update
    win_updates:
      category_names: SecurityUpdates
      state: searched
    register: update_count

  - name: DISPLAY MISSING UPDATE RESULTS
    debug:
      msg: "{{ update_count }}"


#  - name: OBTAIN WINDOW SERVER IP ADDRESS
#    azure_rm_publicipaddress_facts:
#      subscription_id: "{{ my_subscription_id }}"
#      client_id: "{{ my_client_id }}"
#      secret: "{{ my_secret }}"
#      tenant: "{{ my_tenant }}"
#    register: output_ip_address

#  - name: DISPLAY WINDOWS SERVER IP ADDRESS
#    debug:
#      msg: "{{ output_ip_address.ansible_facts.azure_publicipaddresses[0].properties.ipAddress }}"
