---
- name: WINRM
  hosts: wrm

  tasks:

  - name: Update
    win_updates:
#      remote_addr: "{{ azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
    register: reboot

  - name: DISPLAY RESULTS
    debug
      msg: "{{ azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
