---
- name: WINRM
  hosts: localhost

  tasks:

  - name: Update
    win_updates:
      remote_addr: "{{ azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
    register: reboot
