---
- name: WINRM SERVER TEST
  hosts: localhost
  vars:
    my_resource_group: MyResourceGroup
    my_vm_name: anspocw2012
    my_vn_name: poc-vn
    my_sn_name: poc-sn

  tasks:
  - name: OBTAIN IP ADDRESS
#    azure_rm_virtualmachineimage_facts:
    azure_rm_publicipaddress_facts:
      subscription_id: "{{ my_subscription_id }}"
      client_id: "{{ my_client_id }}"
      secret: "{{ my_secret }}"
      tenant: "{{ my_tenant }}"
#      location: eastus
#    register: rawdata


#  - name: Update
#    win_updates:
#      remote_addr: "{{ azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
#    register: reboot

  - name: DISPLAY RESULTS
    debug:
      msg: "{{ ansible_facts.azure_publicipaddresses.ipAddress }}"
